proxy-cache:
  build: .
  ports:
    - "3128:3128"
    - "3141:3141"
    - "3142:3142"
  volumes:
    - /data/proxy-cache/squid/:/var/spool/squid3
    - /data/proxy-cache/devpi:/var/.devpi/server
    - /data/proxy-cache/aptcacherng:/var/cache/apt-cacher-ng
  restart: always
